import type { PatternRaceSettings } from './game-settings';

export type PatternRacePattern = {
  firstLetter: string;
  lastLetter: string;
  length: number | null;
};

export type PatternRaceGuessError = 'pattern_mismatch' | 'not_in_dictionary';

export type PatternRaceHistoryEntry = {
  round: number;
  winnerId: string;
  word: string;
};

export type PatternRaceState = {
  instanceId: string;
  settings: PatternRaceSettings;
  phase: 'playing' | 'round_won' | 'finished';
  round: number;
  pattern: PatternRacePattern;
  usedPatterns: string[];
  scores: Record<string, number>;
  deadline: number | null;
  pausedRemainingMs: number | null;
  nextProblemAt: number | null;
  skipIds: string[];
  roundWinnerId: string | null;
  winningWord: string | null;
  gameWinnerIds: string[];
  history: PatternRaceHistoryEntry[];
};

export type PatternRaceCommand =
  | { kind: 'sync' }
  | { kind: 'submit'; round: number; word: string }
  | { kind: 'skip'; round: number }
  | { kind: 'return_to_setup' };

export function isPatternRaceCommand(
  value: unknown,
): value is PatternRaceCommand {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return false;
  const command = value as Record<string, unknown>;
  const only = (...keys: string[]) =>
    Object.keys(command).every((key) => ['kind', ...keys].includes(key));
  if (command.kind === 'sync' || command.kind === 'return_to_setup')
    return only();
  if (command.kind === 'skip')
    return (
      only('round') &&
      Number.isInteger(command.round) &&
      (command.round as number) >= 1
    );
  return (
    command.kind === 'submit' &&
    only('round', 'word') &&
    Number.isInteger(command.round) &&
    (command.round as number) >= 1 &&
    typeof command.word === 'string' &&
    command.word === command.word.trim() &&
    command.word.length >= 1 &&
    command.word.length <= 40
  );
}

// Familiar, neutral words keep validation predictable and the races accessible.
// Patterns are generated from this list, so every round always has an answer.
export const patternRaceWords = [
  // 3 letters
  'act',
  'air',
  'ant',
  'arm',
  'art',
  'bag',
  'bed',
  'bee',
  'box',
  'boy',
  'bus',
  'cat',
  'cup',
  'day',
  'dog',
  'ear',
  'egg',
  'eye',
  'fan',
  'far',
  'fox',
  'fun',
  'hat',
  'ice',
  'key',
  'map',
  'net',
  'new',
  'oak',
  'one',
  'pen',
  'red',
  'run',
  'sea',
  'sky',
  'tea',
  'ten',
  'top',
  'toy',
  'van',
  'way',
  'web',
  'yes',
  // 4 letters
  'able',
  'acid',
  'aged',
  'also',
  'area',
  'army',
  'away',
  'baby',
  'back',
  'ball',
  'band',
  'bank',
  'base',
  'bath',
  'bear',
  'beat',
  'been',
  'bell',
  'belt',
  'best',
  'bird',
  'blue',
  'boat',
  'body',
  'book',
  'born',
  'both',
  'bowl',
  'busy',
  'cake',
  'calm',
  'card',
  'care',
  'case',
  'city',
  'club',
  'coat',
  'cold',
  'cook',
  'cool',
  'dark',
  'data',
  'date',
  'dawn',
  'desk',
  'door',
  'down',
  'draw',
  'dream',
  'drop',
  'each',
  'earn',
  'easy',
  'edge',
  'else',
  'even',
  'ever',
  'face',
  'fact',
  'farm',
  'fast',
  'feel',
  'film',
  'find',
  'fine',
  'fire',
  'fish',
  'five',
  'food',
  'foot',
  'game',
  'gate',
  'gift',
  'girl',
  'give',
  'glad',
  'goal',
  'gold',
  'good',
  'grow',
  'hair',
  'half',
  'hand',
  'head',
  'help',
  'home',
  'hope',
  'idea',
  'into',
  'item',
  'join',
  'jump',
  'keep',
  'kind',
  'king',
  'lake',
  'land',
  'last',
  'late',
  'leaf',
  'left',
  'life',
  'like',
  'line',
  'lion',
  'live',
  'long',
  'look',
  'love',
  'luck',
  'made',
  'make',
  'many',
  'meal',
  'meet',
  'moon',
  'more',
  'move',
  'name',
  'near',
  'nest',
  'next',
  'nice',
  'note',
  'open',
  'page',
  'park',
  'part',
  'play',
  'rain',
  'read',
  'real',
  'rest',
  'ride',
  'road',
  'room',
  'safe',
  'sand',
  'save',
  'seat',
  'ship',
  'shoe',
  'show',
  'sing',
  'skin',
  'snow',
  'soft',
  'song',
  'star',
  'stay',
  'stop',
  'swim',
  'take',
  'talk',
  'team',
  'time',
  'town',
  'tree',
  'trip',
  'turn',
  'warm',
  'wave',
  'week',
  'well',
  'west',
  'wide',
  'wind',
  'wish',
  'word',
  // 5 letters
  'about',
  'above',
  'actor',
  'admit',
  'after',
  'again',
  'agree',
  'ahead',
  'alive',
  'alone',
  'along',
  'apple',
  'aside',
  'beach',
  'begin',
  'black',
  'board',
  'brain',
  'bread',
  'break',
  'bring',
  'brown',
  'build',
  'carry',
  'chair',
  'charm',
  'chase',
  'cheap',
  'check',
  'child',
  'clean',
  'clear',
  'clock',
  'cloud',
  'coast',
  'color',
  'could',
  'dance',
  'early',
  'earth',
  'empty',
  'enjoy',
  'event',
  'every',
  'faith',
  'field',
  'first',
  'floor',
  'focus',
  'force',
  'fresh',
  'friend',
  'front',
  'fruit',
  'funny',
  'glass',
  'green',
  'group',
  'happy',
  'heart',
  'horse',
  'house',
  'human',
  'laugh',
  'learn',
  'light',
  'magic',
  'match',
  'maybe',
  'metal',
  'money',
  'month',
  'music',
  'night',
  'north',
  'ocean',
  'offer',
  'often',
  'paper',
  'party',
  'peace',
  'phone',
  'place',
  'plant',
  'point',
  'power',
  'proud',
  'quick',
  'quiet',
  'reach',
  'ready',
  'right',
  'river',
  'round',
  'share',
  'short',
  'smile',
  'sound',
  'south',
  'space',
  'sport',
  'stand',
  'start',
  'stone',
  'story',
  'sweet',
  'table',
  'teach',
  'thank',
  'their',
  'there',
  'thing',
  'think',
  'today',
  'train',
  'under',
  'visit',
  'watch',
  'water',
  'white',
  'whole',
  'woman',
  'world',
  'write',
  'young',
  // 6 letters
  'across',
  'animal',
  'answer',
  'around',
  'autumn',
  'beauty',
  'better',
  'bright',
  'camera',
  'change',
  'choice',
  'circle',
  'coffee',
  'corner',
  'create',
  'dinner',
  'family',
  'flower',
  'forest',
  'future',
  'garden',
  'gentle',
  'golden',
  'ground',
  'growth',
  'island',
  'little',
  'market',
  'memory',
  'minute',
  'moment',
  'nature',
  'orange',
  'people',
  'planet',
  'please',
  'pocket',
  'pretty',
  'purple',
  'reason',
  'school',
  'screen',
  'season',
  'simple',
  'sister',
  'smooth',
  'spring',
  'street',
  'strong',
  'summer',
  'travel',
  'useful',
  'valley',
  'window',
  'winter',
  // 7 letters
  'another',
  'balance',
  'because',
  'believe',
  'blanket',
  'brother',
  'central',
  'country',
  'evening',
  'example',
  'freedom',
  'holiday',
  'journey',
  'kitchen',
  'message',
  'morning',
  'natural',
  'outside',
  'picture',
  'problem',
  'rainbow',
  'special',
  'station',
  'student',
  'sunrise',
  'thought',
  'together',
  'weather',
  // 8+ letters
  'airplane',
  'birthday',
  'building',
  'butterfly',
  'calendar',
  'campfire',
  'computer',
  'elephant',
  'favorite',
  'festival',
  'football',
  'friendly',
  'happiness',
  'hospital',
  'important',
  'language',
  'mountain',
  'notebook',
  'painting',
  'playground',
  'sandwich',
  'shoulder',
  'snowflake',
  'sunlight',
  'tomorrow',
  'triangle',
  'vacation',
  'wonderful',
] as const;

export function normalizePatternRaceGuess(value: string) {
  return value.trim().toLowerCase();
}

export function matchesPattern(word: string, pattern: PatternRacePattern) {
  const normalized = normalizePatternRaceGuess(word);
  return (
    (pattern.length === null || normalized.length === pattern.length) &&
    normalized.startsWith(pattern.firstLetter.toLowerCase()) &&
    normalized.endsWith(pattern.lastLetter.toLowerCase())
  );
}

export function generatePatternRacePattern(
  settings: PatternRaceSettings,
  random: () => number = Math.random,
  usedPatterns: readonly string[] = [],
): PatternRacePattern | null {
  const used = new Set(usedPatterns);
  const candidates = [
    ...new Map(
      patternRaceWords.map((word) => {
        const pattern = {
          firstLetter: word[0].toUpperCase(),
          lastLetter: word[word.length - 1].toUpperCase(),
          length: settings.wordLengthMode === 'limited' ? word.length : null,
        };
        return [patternRaceKey(pattern), pattern] as const;
      }),
    ).entries(),
  ]
    .filter(([key]) => !used.has(key))
    .map(([, pattern]) => pattern);
  const index = Math.min(
    candidates.length - 1,
    Math.floor(random() * candidates.length),
  );
  return candidates[Math.max(0, index)] ?? null;
}

export function patternRaceKey(pattern: PatternRacePattern) {
  return `${pattern.firstLetter}:${pattern.lastLetter}:${pattern.length ?? '*'}`;
}
